INSERT INTO article (title, content, created_at, updated_at) VALUES ('김민철', '김민철', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박준형', '박준형', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박민규', '박민규', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('김민철', '김민철', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박준형', '박준형', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박민규', '박민규', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('김민철', '김민철', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박준형', '박준형', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박민규', '박민규', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('김민철', '김민철', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박준형', '박준형', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박민규', '박민규', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('김민철', '김민철', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박준형', '박준형', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박민규', '박민규', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('김민철', '김민철', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박준형', '박준형', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박민규', '박민규', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('김민철', '김민철', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박준형', '박준형', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박민규', '박민규', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('김민철', '김민철', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박준형', '박준형', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박민규', '박민규', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('김민철', '김민철', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('김민철', '김민철', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박준형', '박준형', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박민규', '박민규', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('김민철', '김민철', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박준형', '박준형', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('박민규', '박민규', NOW(), NOW())
INSERT INTO article (title, content, created_at, updated_at) VALUES ('김민철', '김민철', NOW(), NOW())



